# Generated by Django 4.0.1 on 2022-01-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=250, verbose_name='Yorum'),
        ),
    ]
